import React, {useMemo, useRef, useState} from 'react';
import {FlatList, Linking, Pressable, StyleSheet,  TextInput, View} from 'react-native';
import {WebView, WebViewMessageEvent} from 'react-native-webview';
import * as Location from 'expo-location';
import {Point} from './api';
import {Api} from './api';
import {LEAFLET_CSS, LEAFLET_JS} from './generated/leaflet';
import {T} from './translation';
import {AppText} from './NativeTypography';
type Candidate={lat:number;lon:number;label:string};
const inBounds=(lat:number,lon:number)=>Number.isFinite(lat)&&Number.isFinite(lon)&&lat>=-90&&lat<=90&&lon>=-180&&lon<=180;
export function MapPicker({lang,api,initialPoint,onChoose,onCancel,onFailure}:{lang:string;api:Api;initialPoint?:Point|null;onChoose:(p:Point)=>void;onCancel:()=>void;onFailure:(error:unknown)=>void}) {
 const web=useRef<WebView>(null);const [query,setQuery]=useState(''),[results,setResults]=useState<Candidate[]>([]),[candidate,setCandidate]=useState<Candidate|null>(initialPoint||null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const t=(key:string)=>T(lang,key);
 const html=useMemo(()=>`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data: https://tile.openstreetmap.org; connect-src https://tile.openstreetmap.org; font-src data:"><style>html,body,#map{height:100%;margin:0}.route-share-pin{background:transparent;border:0}.route-share-pin span{display:block;width:20px;height:20px;border:3px solid white;border-radius:50%;background:#153C32;box-shadow:0 1px 5px #315849}${LEAFLET_CSS}</style></head><body><div id="map"></div><script>${LEAFLET_JS}</script><script>const map=L.map('map').setView([17.2,79.3],8);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap contributors</a>'}).addTo(map);let marker=null;function notify(ll){window.ReactNativeWebView.postMessage(JSON.stringify({type:'candidate',lat:ll.lat,lon:ll.lng}));}function pin(ll,send){if(marker){marker.setLatLng(ll);}else{marker=L.marker(ll,{draggable:true,icon:L.divIcon({className:'route-share-pin',html:'<span></span>',iconSize:[24,24],iconAnchor:[12,12]})}).addTo(map);marker.on('dragend',e=>notify(e.target.getLatLng()));}if(send)notify(ll);}map.on('click',e=>pin(e.latlng,true));window.setCandidate=(lat,lon)=>{const ll=L.latLng(lat,lon);map.setView(ll,14);pin(ll,false);};</script></body></html>`,[]);
 const setPin=(item:Candidate,center=false)=>{if(!inBounds(item.lat,item.lon))return;setCandidate(item);setError('');if(center)web.current?.injectJavaScript(`window.setCandidate(${item.lat},${item.lon});true;`);};
 const onMessage=(e:WebViewMessageEvent)=>{try{const raw=e.nativeEvent.data;if(typeof raw!=='string'||raw.length>512)return;const d=JSON.parse(raw);if(!d||typeof d!=='object'||d.type!=='candidate'||!inBounds(d.lat,d.lon))return;setPin({lat:d.lat,lon:d.lon,label:t('mapSelectedPoint')});}catch{}};
 const useCurrent=async()=>{setBusy(true);setError('');try{const permission=await Location.requestForegroundPermissionsAsync();if(!permission.granted){setError(t('mapLocationDenied'));return;}const location=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});const {latitude,longitude}=location.coords;if(!inBounds(latitude,longitude)){setError(t('mapLocationError'));return;}setPin({lat:latitude,lon:longitude,label:t('mapCurrentLocation')},true);}catch{setError(t('mapLocationError'));}finally{setBusy(false);}};
 const search=async()=>{const term=query.trim();if(term.length<3||term.length>160){setError(t('mapSearchRequired'));return;}setBusy(true);setError('');try{const result=await api.request(`/api/places?q=${encodeURIComponent(term)}&lang=${encodeURIComponent(lang)}`);const rows=Array.isArray(result.places)?result.places:[];const next=rows.map((p:any)=>({label:String(p.label||'').slice(0,180),lat:Number(p.lat),lon:Number(p.lon)})).filter((p:Candidate)=>p.label&&inBounds(p.lat,p.lon)).slice(0,6);setResults(next);if(next.length===0)setError(t('mapSearchEmpty'));}catch(e){onFailure(e);setError(t('mapSearchError'));setResults([]);}finally{setBusy(false);}};
 const chooseResult=(p:Candidate)=>{if(!inBounds(p.lat,p.lon))return;setPin(p,true);};
 const nav=({url,isTopFrame}:{url:string;isTopFrame?:boolean})=>{if(isTopFrame===false)return true;if(url==='about:blank'||url==='https://localhost'||url==='https://localhost/')return true;try{const target=new URL(url);if(target.origin==='https://www.openstreetmap.org'&&target.pathname==='/copyright'&&!target.search&&!target.hash)void Linking.openURL('https://www.openstreetmap.org/copyright');}catch{/* block malformed navigation */}return false;};
 return <View style={styles.wrap}><View style={styles.head}><AppText style={styles.title}>{t('mapPickTitle')}</AppText><AppText style={styles.help}>{t('mapSearchHelp')}</AppText><AppText style={styles.help}>{t('mapProviderNotice')}</AppText><Pressable accessibilityRole="link" onPress={()=>void Linking.openURL('https://operations.osmfoundation.org/policies/nominatim/')}><AppText style={styles.policy}>{t('mapProviderPolicy')}</AppText></Pressable><View style={styles.searchRow}><TextInput accessibilityLabel={t('mapSearchLabel')} value={query} onChangeText={setQuery} onSubmitEditing={()=>void search()} placeholder={t('mapSearchLabel')} style={[styles.input,{fontFamily:lang==='te'?'AnekTelugu400':'Manrope400',lineHeight:lang==='te'?24:undefined}]}/><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void search()} style={styles.search}><AppText style={styles.searchText}>{t('mapSearch')}</AppText></Pressable></View><View style={styles.tools}><Pressable disabled={busy} onPress={()=>void useCurrent()} style={styles.gps}><AppText style={styles.gpsText}>{busy?t('mapLocationBusy'):t('mapMyLocation')}</AppText></Pressable>{error?<AppText style={styles.error}>{error}</AppText>:null}</View><FlatList horizontal data={results} keyExtractor={(p,i)=>`${p.label}-${i}`} contentContainerStyle={styles.results} renderItem={({item})=><Pressable onPress={()=>chooseResult(item)} style={styles.result}><AppText numberOfLines={2} style={styles.resultText}>{item.label}</AppText></Pressable>}/></View><WebView ref={web} source={{html,baseUrl:'https://localhost'}} originWhitelist={['about:blank','https://localhost']} javaScriptEnabled onLoadEnd={()=>{if(initialPoint&&inBounds(initialPoint.lat,initialPoint.lon))web.current?.injectJavaScript(`window.setCandidate(${initialPoint.lat},${initialPoint.lon});true;`);}} onMessage={onMessage} onShouldStartLoadWithRequest={nav} applicationNameForUserAgent="RouteShareLocalBeta/0.1" style={styles.map}/><View style={styles.footer}>{candidate?<AppText numberOfLines={1} style={styles.selected}>{t('mapSelectedPoint')}: {candidate.label}</AppText>:<AppText style={styles.selected}>{t('locationNotChosen')}</AppText>}<View style={styles.buttons}><Pressable accessibilityRole="button" onPress={onCancel} style={styles.cancel}><AppText style={styles.cancelText}>{t('mapCancel')}</AppText></Pressable><Pressable accessibilityRole="button" disabled={!candidate} onPress={()=>candidate&&onChoose({label:candidate.label,lat:candidate.lat,lon:candidate.lon})} style={[styles.confirm,!candidate&&styles.disabled]}><AppText style={styles.confirmText}>{t('mapUsePoint')}</AppText></Pressable></View></View></View>;
}
const styles=StyleSheet.create({wrap:{flex:1,backgroundColor:'#F5F4EC'},head:{padding:12,gap:7},title:{fontSize:21,fontWeight:'800',color:'#153C32'},help:{color:'#71857B',fontSize:13},policy:{color:'#153C32',fontSize:12,fontWeight:'700',textDecorationLine:'underline'},searchRow:{flexDirection:'row',gap:7},input:{flex:1,minHeight:42,borderWidth:1,borderColor:'#DCE4D8',borderRadius:12,paddingHorizontal:12,color:'#315849'},search:{borderRadius:12,backgroundColor:'#153C32',justifyContent:'center',paddingHorizontal:13},searchText:{color:'#F5F4EC',fontWeight:'800'},tools:{flexDirection:'row',alignItems:'center',gap:10},gps:{alignSelf:'flex-start',paddingVertical:7,paddingHorizontal:10,borderRadius:12,backgroundColor:'#E9EEE6'},gpsText:{color:'#153C32',fontWeight:'700'},error:{color:'#8A3C2A'},results:{gap:8},result:{maxWidth:210,padding:9,borderRadius:12,backgroundColor:'#E7EDE2'},resultText:{color:'#315849',fontSize:12},empty:{color:'#71857B'},map:{flex:1},footer:{padding:13,borderTopWidth:1,borderColor:'#DCE4D8',gap:8},selected:{color:'#315849',fontWeight:'700'},buttons:{flexDirection:'row',gap:9},cancel:{flex:1,padding:13,borderRadius:13,backgroundColor:'#E9EEE6',alignItems:'center'},confirm:{flex:1,padding:13,borderRadius:13,backgroundColor:'#153C32',alignItems:'center'},cancelText:{color:'#153C32',fontWeight:'800'},confirmText:{color:'#FFFFFF',fontWeight:'800'},disabled:{opacity:.4}});
